### ISSUE TITLE
Sort out maintenance of josm-geojson plugin

### ISSUE THREAD

**Issue by don-vip** [iandees/josm-geojson#3]
Hi,
We require for plugins to either:
- be actively maintained by someone (original author or not)
- or allow us to maintain it (when there is breaking core changes for example)

This works pretty well for majority of plugins, but I struggle on this one. If I understand the current situation:
- this repository is no longer active
- its fork (https://github.com/matthieun/josm-geojson) is no longer active
- the fork of its fork (https://github.com/Larry0ua/josm-geojson/pull/1#issuecomment-227403465) is no longer active

This situation is crazy. I totally understand that people lose interest in maintaining a JOSM plugin, but in this case forking over and over is a waste of our time to understand the situation, who is the maintainer, etc.

A better solution would be to merge fork commits to this original repository, then transfer it to the JOSM Github organization. All of you would still have commit privileges if you want to, but it would be simpler to understand, and we could maintain the plugin ourselves.

Would it be ok for you?

**Comment by iandees** [comment]
To be honest I never considered this working. I'm surprised folks are using it 😄 . I don't remember ever adding it to the JOSM Plugins page...

Anyway, it probably does make sense to move this (and the other couple JOSM plugins I have) over to the JOSM organization. If you add me I can transfer ownership.

**Comment by don-vip** [comment]
Ok thanks ! I'll add you tonight :)

**Comment by don-vip** [comment]
You're now team maintainer of https://github.com/orgs/JOSM/teams/geojson so I think you can transfer the repository. I have invited @matthieun and @Larry0ua as well.

**Comment by matthieun** [comment]
I have also never added it to the list of official JOSM plugins...
What is the official version now? The link above gives me a 404...

**Comment by don-vip** [comment]
This is strange, the repo is available at https://github.com/JOSM/josm-geojson but it still exist here, I don't understand why.
