### ISSUE TITLE
Cannot read WGS84 by QGIS

### ISSUE THREAD

**Issue by DenisCarriere** [iandees/josm-geojson#4]
I have a GeoJSON that was created by QGIS using WGS84.

The plugin cannot read **urn:ogc:def:crs:OGC:1.3:CRS84** which is an OGC projection.

```
INFO: Open file: /Users/mac/Documents/Roads_WGS84.geojson (18109785 bytes)
INFO: Parsing GeoJSON: /Users/mac/Documents/Roads_WGS84.geojson
ERROR: Unknown CRS urn:ogc:def:crs:OGC:1.3:CRS84
ERROR: Error while reading json file!
```

**Comment by tomwyr** [comment]
I've had the same issue while trying to load GeoJSON. Simply deleting following line in the file did the job in my case.
`"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },`

Looks like it uses WGS84 by default or tries to guess proper crs depending on given coordinates.

**Comment by iandees** [comment]
Sorry, I didn't see this ticket earlier. 

The GeoJSON spec specifically removed CRS support and assumes EPSG:4326. If you can, it would be best to load speech compliant GeoJSON.

**Comment by nmtoken** [comment]
**GeoJSON is not EPSG:4326** 

EPSG:4326 is WGS84 with coordinates in latitude / longitude  order.   @DenisCarriere is correct GeoJSON is urn:ogc:def:crs:OGC:1.3:CRS84, which is  WGS84 with coordinates in longitude/latitude order

**Comment by iandees** [comment]
Yes, you're right I got the codes wrong. But my point stands: the GeoJSON spec [doesn't support alternative CRS's](https://tools.ietf.org/html/rfc7946#section-4), so this plugin doesn't.
