### ISSUE TITLE
related to JOSM/geojson repo?

### ISSUE THREAD

**Issue by harry-wood** [iandees/josm-geojson#5]
A web search for "JOSM GeoJSON" is finding this repo, but how does it relate to https://github.com/JOSM/geojson  Looks like that's a more recently updated fork (but not labelled as a fork). Searching for GeoJSON plugins from within JOSM will only find that other repo.

**Comment by iandees** [comment]
Related to https://github.com/iandees/josm-geojson/issues/3. I think they copied it over but didn't make it a fork/move it.
